### ISSUE TITLE
Sort on Multiple Columns

### ISSUE THREAD

**Issue by smokinpuppy** [joequery/Stupid-Table-Plugin#112]
Is it possible to use Stupid Table to sort on multiple columns? Both on load and by clicking shift while clicking on the <th>.

Thank you,

Robert

**Comment by meirg** [comment]
+1 for this feature

**Comment by keithpickering** [comment]
Any updates on this? I can't find a plugin that allow multi column sorting.

**Comment by Metacowboy** [comment]
Bum +1 this is a must have for table sorting .

**Comment by y471n** [comment]
+1 for this feature

**Comment by ChristianTheMinery** [comment]
+1 for this

**Comment by keithpickering** [comment]
2 years and no updates? This is the best table sorting plugin available, and it's just missing this one feature. Every other similar plugin tries to be an entire table sorting suite - this is the only non-bloated one.

**Comment by joequery** [comment]
Hey Keith,

Thanks for the kind words regarding the plugin. As of late, what usually happens is that once or twice a year I try to knock out a few PRs and Issues for this plugin. I unfortunately cannot guarantee a time when this feature will be implemented.

I have considered handing the plugin over to the community but I'm afraid of bloat ruining the vision I had for the stupid table in the first place. So unfortunately progress on the plugin is slow because I'm too nervous about handing over the reins but also do not have the time to keep up with the issues/PRs.

**Comment by ChristianTheMinery** [comment]
Is the plugin set up to handle easy extending? If it's not, then maybe that could be a development priority, and the community could write extensions for the core plugin, which would remain the same. Lord knows I've written some crazy extra JavaScript on top of your existing plugin, it would be great to be able to formalize some of that into an extension and release it.

**Comment by joequery** [comment]
That's a good idea Christian. There had been talk of something similar before but I hadn't followed through. I think making that a priority makes the most sense.

**Comment by mdi** [comment]
👍 on this feature.

**Comment by joequery** [comment]
Good news folks. #187 makes this achievable in the near future. I've been resuming development on this project lately.

**Comment by joequery** [comment]
Good news everyone. Multicolumn sort has been added via #188. Sorry it took 3 years, but better late than never I suppose!
