### ISSUE TITLE
Sorting only works when there is more than 2 rows

### ISSUE THREAD

**Issue by daath** [joequery/Stupid-Table-Plugin#190]
So, I was confused - It looks like sorting only works when there is more than 2 rows...

**Comment by joequery** [comment]
Oh my. Can't say that is something I tested for! I'll try to replicate.

**Comment by daath** [comment]
It's actually much worse.... The sorting doesn't work properly if there is an even number of rows in the table...

**Comment by joequery** [comment]
Hm. That would be very interesting if that has happened for so long! Can
you create a fiddle to replicate?

**Comment by daath** [comment]
There is probably a way easier way to reproduce it, but here is an ugly one:

https://jsfiddle.net/d53pvft2/

That one works, but if you uncomment the line:

`//        ,'ripple': 8`

OR comment out the line:

`        ,'tron': 7`

Then there will be an even number of rows, and it stops working...

**Comment by joequery** [comment]
Thank you, I'll take a look.

**Comment by joequery** [comment]
Will be working on this branch here - https://github.com/joequery/Stupid-Table-Plugin/tree/issue_190

I believe this is an issue with dynamically adding table rows. Static tables of even length are fine.

**Comment by joequery** [comment]
The issue was that `stupidtable()` was being called multiple times on the same table. `stupidtable()` should only be called once to initialize the table. You can use `stupidsort()` on a specific `th` to programatically sort the table. 

I have updated the fiddle here to a working state using these principles. I apologize if the documentation was not clear on this.

https://jsfiddle.net/d53pvft2/1/

**Comment by daath** [comment]
Aah, sorry then! Maybe do an alert if you try to initialize more than once (like DataTables) :)

Thanks for looking into it and clearing it up! :)
